### ISSUE TITLE
Ubuntu Mate 17 - ImportError: libwx_gtk3u_html-3.0.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by trayres** [WikidPad/WikidPad#22]
Traceback (most recent call last):
  File "WikidPad.py", line 1, in <module>
    import WikidPadStarter
  File "/home/trayres/ext_gitrepos/WikidPad/WikidPadStarter.py", line 111, in <module>
    from pwiki.MainApp import App, findDirs
  File "lib/pwiki/MainApp.py", line 12, in <module>
    import wx, wx.xrc
  File "/home/trayres/.local/lib/python2.7/site-packages/wx/xrc.py", line 10, in <module>
    from ._xrc import *
ImportError: libwx_gtk3u_html-3.0.so.0: cannot open shared object file: No such file or director

**Comment by xkjq** [comment]
Make sure you have the wx prerequisites installed.

With the latest version you'll be wanting wxPython 4.0.1 (though they should be similar for previous versions).

https://github.com/wxWidgets/Phoenix/blob/wxPython-4.0.1/README.rst

**Comment by BjornFJohansson** [comment]
Try using the anaconda python distribution. It makes these things much simpler.
