### ISSUE TITLE
I cant run on Debian

### ISSUE THREAD

**Issue by gerroon** [WikidPad/WikidPad#44]
Hi

I tried these on Debian Buster but I get bunch of errors. See my installed packages at the bottom

```
python3 WikidPad.py 
Traceback (most recent call last):
  File "WikidPad.py", line 6, in <module>
    from WikidPad import WikidPadStarter
  File "/opt/WikidPad/WikidPad/WikidPadStarter.py", line 112, in <module>
    from pwiki.MainApp import App, findDirs
  File "/opt/WikidPad/WikidPad/lib/pwiki/MainApp.py", line 30, in <module>
    from . import WindowLayout
  File "/opt/WikidPad/WikidPad/lib/pwiki/WindowLayout.py", line 10, in <module>
    from .wxHelper import LayerSizer, ProxyPanel
  File "/opt/WikidPad/WikidPad/lib/pwiki/wxHelper.py", line 7, in <module>
    from wx.siplib import unwrapinstance
ModuleNotFoundError: No module named 'wx.siplib'
```

```
python WikidPad.py 
Traceback (most recent call last):
  File "WikidPad.py", line 6, in <module>
    from WikidPad import WikidPadStarter
  File "/opt/WikidPad/WikidPad/WikidPadStarter.py", line 14, in <module>
    origin = __spec__.origin
NameError: name '__spec__' is not defined
```

```
apt list |grep -i python-wx

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

python-wxgtk-media3.0/testing,now 3.0.2.0+dfsg-8 amd64 [installed]
python-wxgtk-media3.0/testing 3.0.2.0+dfsg-8 i386
python-wxgtk-media4.0/testing 4.0.1+dfsg-6+b1 amd64
python-wxgtk-media4.0/testing 4.0.1+dfsg-6+b1 i386
python-wxgtk-webview3.0/testing,now 3.0.2.0+dfsg-8 amd64 [installed]
python-wxgtk-webview3.0/testing 3.0.2.0+dfsg-8 i386
python-wxgtk-webview4.0/testing 4.0.1+dfsg-6+b1 amd64
python-wxgtk-webview4.0/testing 4.0.1+dfsg-6+b1 i386
python-wxgtk3.0-dev/testing,testing,now 3.0.2.0+dfsg-8 all [installed]
python-wxgtk3.0/testing,now 3.0.2.0+dfsg-8 amd64 [installed,automatic]
python-wxgtk3.0/testing 3.0.2.0+dfsg-8 i386
python-wxgtk4.0/testing,now 4.0.1+dfsg-6+b1 amd64 [installed]
python-wxgtk4.0/testing 4.0.1+dfsg-6+b1 i386
python-wxtools/testing,testing,now 3.0.2.0+dfsg-8 all [installed]
python-wxversion/testing,testing,now 3.0.2.0+dfsg-8 all [installed,automatic]

```

**Comment by butscher** [comment]
WikidPad 2.4 requires at least Python 3.4 and wxPython 4.0 (Phoenix). Probably you have a lower Python version which uses the wrong wxPython.

**Comment by gerroon** [comment]
Ok thanks, I will see what I can with it

**Comment by benkinooby** [comment]
Closing this issue for inactivity. Hope that's OK for your @gerroon . If your issue still persists, a new issue might be the preferable option since a lot has changed since your report.
