### ISSUE TITLE
Funny error in extension.

### ISSUE THREAD

**Issue by iiiCpu** [WikidPad/WikidPad#47]
Hello there!

I made tag search extension not so long ago.

https://groups.google.com/forum/#!topic/wikidpad-devel/befC0Q6ZHlo
File itself: https://pastebin.com/YPnBTxur

It worked fine just a few releases ago. And now it breaks  with funny error
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\WikidPad\extensions\HtmlExporter.py", line 1698, in _actualProcessInsertion
  File "C:\Program Files (x86)\WikidPad\extensions\searchtags.py", line 138, in createContent
  File "C:\Program Files (x86)\WikidPad\extensions\searchtags.py", line 120, in calc
  File "C:\Program Files (x86)\WikidPad\extensions\searchtags.py", line 37, in 
TypeError: unbound method f_and() must be called with TagHandler instance as first argument (got TagHandler instance instead)
```
I'm not Parseltongue guy and I have no idea what this "_T is not T_" error is about. 
Any clue?

**Comment by butscher** [comment]
Which WikidPad version do you use?

**Comment by iiiCpu** [comment]
2.3rc02
I tested it on 2.2 and somehow it didn't work either. Now I wonder if it's because of different Python versions as I used the most recent during development.

**Comment by iiiCpu** [comment]
Ok, simply syntax. All I had to do is to move logical operators from class to global space. I'm surely not a parseltongue person.

Here's fixed version
https://pastebin.com/R6iB1gB3

Sorry for bothering. Good day!
