### ISSUE TITLE
Pages getting lost - 

### ISSUE THREAD

**Issue by wwwald** [WikidPad/WikidPad#48]
Since some time, I'm having problems with Wikidpad where it will regularly start complaining about write access to the database (when saving a page). When this occurs, the current page content is not saved anymore, and restarting Wikidpad results in the corresponding file on disk being removed, and the page being empty after restart.
For completeness sake: my wiki is stored in my local Dropbox folder for syncing across multiple computers - although that has never given me problems before.

I've `git pull`ed my Wikidpad code and am currently running the latest 2.4 alpha 1 code, with wxPython 4.0.4 and SQLite 3.27.2. But the problem still shows.

My error log shows multiple entries like the one below, so I suspect this is the cause of the problem:

    Version: 'wikidPad 2.4alpha01' Session start: 2019-04-11 14:46:25
    Traceback (most recent call last):
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\wikidata\original_sqlite\WikiData.py", line 316, in setContent
        "wikiPageFiles_writeFileMode", 0))
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\StringOps.py", line 439, in writeEntireFile
        os.rename(tempPath, filename)
    FileExistsError: [WinError 183] Cannot create a file when that file already exists: '\\\\?\\E:\\Dropbox\\config\\vitowiki\\data\\tmpw_1u7mbj.wiki' -> '\\\\?\\E:\\Dropbox\\config\\vitowiki\\data\\%2D20190411-.wiki'
    File "WikidPad.py", line 13, in <module>
        WikidPadStarter.main()
    File "E:\Dropbox\apps\wikidpad\WikidPad\WikidPadStarter.py", line 235, in main
        app.MainLoop()
    File "C:\Users\STANDAEA\AppData\Local\Continuum\miniconda3\envs\wikidpad3\lib\site-packages\wx\core.py", line 2166, in MainLoop
        rv = wx.PyApp.MainLoop(self)
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\PersonalWikiFrame.py", line 1651, in <lambda>
        lambda evt: (self.saveAllDocPages(),
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\PersonalWikiFrame.py", line 3848, in saveAllDocPages
        self.fireMiscEventProps({"saving all pages": None, "force": force})
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\MiscEvent.py", line 37, in fireMiscEventProps
        shareListenerList=shareListenerList).processSend(first)
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\MiscEvent.py", line 359, in processSend
        l.miscEventHappened(self)
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\DocPagePresenter.py", line 533, in miscEventHappened
        return BasicDocPagePresenter.miscEventHappened(self, miscevt)
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\DocPagePresenter.py", line 152, in miscEventHappened
        self.fireMiscEventProps(miscevt.getProps())
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\MiscEvent.py", line 37, in fireMiscEventProps
        shareListenerList=shareListenerList).processSend(first)
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\MiscEvent.py", line 365, in processSend
        traceback.print_stack()
    Traceback (most recent call last):
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\wikidata\original_sqlite\WikiData.py", line 316, in setContent
        "wikiPageFiles_writeFileMode", 0))
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\StringOps.py", line 439, in writeEntireFile
        os.rename(tempPath, filename)
    FileExistsError: [WinError 183] Cannot create a file when that file already exists: '\\\\?\\E:\\Dropbox\\config\\vitowiki\\data\\tmpw_1u7mbj.wiki' -> '\\\\?\\E:\\Dropbox\\config\\vitowiki\\data\\%2D20190411-.wiki'

How to fix this?

**Comment by benkinooby** [comment]
Closing this after 7 years without response. Happy to re-open or work on it as a new issue if needed.
