### ISSUE TITLE
Temporary files in use by another process

### ISSUE THREAD

**Issue by wwwald** [WikidPad/WikidPad#62]
Since a few weeks, I'm running regularly into trouble when saving newly created wiki pages.

The error message that pops up is always similar to this:

![image](https://user-images.githubusercontent.com/39531/84124164-22b06780-aa3b-11ea-9916-2c7ef65b3e1c.png)

In the error log, it's always about a `DbWriteAccessError` in the SQLite database:

    Traceback (most recent call last):
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\WikiTxtCtrl.py", line 3629, in OnDoubleClick
        if not self.activateLink(wx.Point(x, y)):
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\WikiTxtCtrl.py", line 2517, in activateLink
        return self.activateTokens(tokens, tabMode)
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\WikiTxtCtrl.py", line 2383, in activateTokens
        suggNewPageTitle=suggNewPageTitle)
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\DocPagePresenter.py", line 276, in openWikiPage
        self.loadWikiPage(page, **evtprops)
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\DocPagePresenter.py", line 293, in loadWikiPage
        self.getSubControl("textedit").loadWikiPage(page, evtprops)
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\WikiTxtCtrl.py", line 1043, in loadWikiPage
        self.unloadCurrentDocPage(evtprops)
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\WikiTxtCtrl.py", line 959, in unloadCurrentDocPage
        self.saveLoadedDocPage()
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\WikiTxtCtrl.py", line 939, in saveLoadedDocPage
        if self.presenter.getMainControl().saveDocPage(page):
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\PersonalWikiFrame.py", line 3889, in saveDocPage
        page.writeToDatabase()
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\DocPages.py", line 284, in writeToDatabase
        self._save(text, fireEvent=fireEvent)
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\DocPages.py", line 2027, in _save
        self.getWikiData().setContent(self.wikiPageName, text)
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\WikiDocument.py", line 259, in __call__
        return self.callFunction(*args, **kwargs)
    File "E:\Dropbox\apps\wikidpad\WikidPad\lib\pwiki\wikidata\original_sqlite\WikiData.py", line 324, in setContent
        raise DbWriteAccessError(e)
    pwiki.WikiExceptions.DbWriteAccessError: [WinError 32] The process cannot access the file because it is being used by another process: '\\\\?\\E:\\Dropbox\\config\\vitowiki\\data\\tmp6mfof819.wiki' -> '\\\\?\\E:\\Dropbox\\config\\vitowiki\\data\\%2D2020-05-.wiki'

I already rebuilt this wiki completely, so it doesn't seem to be an issue at the database level at first sight. 

Any clues?

**Comment by vashnt707** [comment]
Most likely Dropbox or any security software's locks causing issue.

**Comment by benkinooby** [comment]
@wwwald from your error log I assume you're using original sqlite database format [1]

Please try:

1. close WikidPad
2. stop Dropbox (wait a minute or so for it to completely spin down)
3. move `tmp6mfof819.wiki` and `%2D2020-05-.wiki` somewhere outside Dropbox if they are of value to you, otherwise delete them
4. open WikidPad
5. rebuild database
6. try to reproduce this error (create new wiki page)
7. close WikidPad
8. start Dropbox (wait a minute or so for it to completely spin up)
9. try to reproduce this error (create new wiki page)

To me, it looks like something went sideways when creating/renaming a wikiword (`tmp6mfof819.wiki` and `%2D2020-05-.wiki` are very odd wikiwords, especially with the % as first character).

When I shared my Wikis via Dropbox, I always used original sqlite format and excluded `wikiovw.sli` from syncing.

[1] https://wikidpad.sourceforge.net/help/WhereIsTheDataStored.html
