### ISSUE TITLE
WikidPad 2.4alpha installation on Linux via pip

### ISSUE THREAD

**Issue by gchriz** [WikidPad/WikidPad#72]
In issue #61 Björn Johansson wrote:

> Hi all, There is a crude untested wikidpad setuptools package reflecting my latest working wikidpad. 
>
> Install by:
> 
> `pip install WikidPadMP==2.4a1.dev2`

Thanks!

I tried it on my Fedora 33 system.

To be independent from the Fedora packages (Python, wxpython) and not to mix up my system I used a virtualenv for it.

The automatic build process of the local wxpython stopped with an error due to missing development package(s).

==> sudo dnf install gtk3-devel

Then it compiled without further problems.

But it didn't start. A syntax error...

In file WikidPad/lib/pwiki/DiffGui.py  in line 473 
        self.StartStyling(self.GetLength() # , 0xff)  # changed here !
there was a closing parenthesis missing (commented out by mistake)

It should be:
        self.StartStyling(self.GetLength()) # , 0xff)  # changed here !

Then WikidPad started!   Yeah!

Unfortunately it didn't close properly. I had to kill it. 

More testing will follow in the next days.

**Comment by BjornFJohansson** [comment]
Great! You are correct, this was my typo. I do not know how this passed on my setup? 
Perhaps this was never called on my computer.

**Comment by BjornFJohansson** [comment]
@gchriz Could you list the packages with versions that you run?

**Comment by BjornFJohansson** [comment]
I run this:
wikidPad version: wikidPad 2.4alpha01dev2
Python version: 3.8.5 | packaged by conda-forge | (default, Aug 29 2020, 01:22:49) 
[GCC 7.5.0]
wx versionx: 4.1.0 gtk2 (phoenix) wxWidgets 3.1.4
BioPython version: 1.78
Platform: Linux-5.8.0-43-generic-x86_64-with-glibc2.10

Curiously, when I run on python 3.9, I also can not stop wikidpad.

**Comment by gchriz** [comment]
On 17.02.21 at 10:51 Björn Johansson wrote:

> @gchriz Could you list the packages with versions that you run?

I started with an empty virtual environment and just installed your
WikidPadMP 2.4a1.dev2 using my systems' Python 3.9.1
.

The following got automatically pulled in by pip:

Package         Version
--------------- ----------
appdirs         1.4.4
biopython       1.78
certifi         2020.12.5
chardet         4.0.0
cycler          0.10.0
dateparser      1.0.0
decorator       4.4.2
idna            2.10
kiwisolver      1.3.1
matplotlib      3.3.4
natsort         7.1.1
networkx        2.5
numpy           1.20.1
Pillow          8.1.0
pip             21.0.1
prettytable     2.0.0
pydna           3.1.3
pyparsing       2.4.7
python-dateutil 2.8.1
pytz            2021.1
regex           2020.11.13
requests        2.25.1
scipy           1.6.0
setuptools      49.1.3
six             1.15.0
tzlocal         2.1
urllib3         1.26.3
wcwidth         0.2.5
WikidPadMP      2.4a1.dev2
wxPython        4.1.1


My system is a  Linux 5.10.13-200.fc33.x86_64.


I will do some more experiments with virtual envs, testing different
versions of those packages and perhaps of Python itself.

**Comment by gchriz** [comment]
Unfortunately I haven't found enough time to look into this yet.

But I really needed comfortable access to my WikidPad data in the meantime,

So I wrote an (initially) small tool for just that access as a Linux Bash script mostly using fzf and ripgrep under the hood. 
While using the tool I realized I could extend it to another type of Wiki handling. 
So it grew rapidly...

I really like WikidPad, but having wiki handling possible on the command line as an alternative is really nice.
Probably I'll keep both tracks active - will see.
If there is any interest regarding that tool just let me know.

**Comment by fuse-nine** [comment]
Hi @BjornFJohansson 

Tried WikidPad on Ubuntu 20.04:
$ pip install WikidPadMP==2.4a1.dev2

Started and got an error:


$ wikidpad
123
15:08:14: Debug: Adding duplicate image handler for 'Windows bitmap file'
15:08:14: Debug: Adding duplicate animation handler for '1' type
15:08:14: Debug: Adding duplicate animation handler for '2' type
123
15:08:17: Debug: No accel key found, accel string ignored.
15:08:17: Debug: No accel key found, accel string ignored.
15:08:17: Debug: No accel key found, accel string ignored.
15:08:17: Debug: No accel key found, accel string ignored.
Traceback (most recent call last):
  File "/home/one/.local/lib/python3.8/site-packages/WikidPad/lib/pwiki/MainApp.py", line 227, in OnInit
    return self.initStep2(cmdLine)
  File "/home/one/.local/lib/python3.8/site-packages/WikidPad/lib/pwiki/MainApp.py", line 419, in initStep2
    self.startPersonalWikiFrame(cmdLine)
  File "/home/one/.local/lib/python3.8/site-packages/WikidPad/lib/pwiki/MainApp.py", line 724, in startPersonalWikiFrame
    wikiFrame = PersonalWikiFrame(None, -1, "WikidPad", self.wikiAppDir,
  File "/home/one/.local/lib/python3.8/site-packages/WikidPad/lib/pwiki/PersonalWikiFrame.py", line 356, in __init__
    self.initializeGui()
  File "/home/one/.local/lib/python3.8/site-packages/WikidPad/lib/pwiki/PersonalWikiFrame.py", line 2300, in initializeGui
    self.buildMainMenu()
  File "/home/one/.local/lib/python3.8/site-packages/WikidPad/lib/pwiki/PersonalWikiFrame.py", line 1368, in buildMainMenu
    self.fillTextBlocksMenu(self.textBlocksMenu)
  File "/home/one/.local/lib/python3.8/site-packages/WikidPad/lib/pwiki/PersonalWikiFrame.py", line 1096, in fillTextBlocksMenu
    TextTree.addTreeToMenu(treeData,
  File "/home/one/.local/lib/python3.8/site-packages/WikidPad/lib/pwiki/TextTree.py", line 265, in addTreeToMenu
    menuItem = wx.MenuItem(menu, menuID, item.title)
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at /tmp/pip-install-vid_dr8q/wxpython_262aff3289884d228e5f991d2a3740ce/ext/wxWidgets/src/common/stockitem.cpp(210) in wxGetStockLabel(): invalid stock item ID
OnInit returned false, exiting...



What do you advise?

**Comment by fuse-nine** [comment]
@BjornFJohansson 

~$ python -V
Python 3.8.10

~$ python
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> wx.version()
'4.1.1 gtk3 (phoenix) wxWidgets 3.1.5'
>>> wx.__version__
'4.1.1'
>>>

**Comment by fuse-nine** [comment]
@gchriz

> I really like WikidPad, but having wiki handling possible on the command line as an alternative is really nice.
> Probably I'll keep both tracks active - will see.
> If there is any interest regarding that tool just let me know.

Very interesting
Please write how

**Comment by fuse-nine** [comment]
Hi all!

Launched wikidpad under a different user - it works!
Thanks!
Under work user only as root, sudo
Cons: Wikis change ownership to root.
Something interferes. Tried deleting various configuration files in ~/.config and in ~/.local but couldn't find the cause.
It works, but the session starts slowly until it interprets the content of open pages.
After that too slowly.

Found a great alternative to CudaText: http://cudatext.sourceforge.net/
Multiplatform powerful text editor.
Description https://wiki.freepascal.org/CudaText
With WikigPad lexer, WikigPad plugin, WikigPad_Helper plugin, WikigPad treehelper
https://github.com/CudaText-addons/cuda_wikidpad_helper
installation via Plugins / Addon Manager / Install from GitHub
This plugin allows you to open a wiki file by double clicking on a wiki word.

The session opens instantly, works very fast even with large files.
CudaText builds a TOC tree of the page structure.
Unlike WikigPad, there is a TOC folding and a tree search - a filter.
Filter - headings are selected by keywords.
It is also possible to search in the tree using the CudaExt plugin.
Searching in FindinFiles-v4 files is fast and convenient.
There is a Differ plugin for comparing the contents of files.
The main thing is that there is no database, as in WikidPad, which sometimes "breaks".

Another alternative is the multi-platform Obsidian https://obsidian.md/
It is focused on building its Knowledge Base.
It is also based, like WikigPad, on plain-text.
