### ISSUE TITLE
Python 3.8 deprecates time.clock (and possible other functions)

### ISSUE THREAD

**Issue by deliciouslytyped** [WikidPad/WikidPad#77]
Running WikidPad on Python 3.8 fails with 
```
Traceback (most recent call last):
  File "/nix/store/0qh2p7y4331h1y9jl5gd6fsxqbpwjlnh-wikidpad-master-2019-07-31/WikidPad/lib/pwiki/MainApp.py", line 227, in OnInit
    return self.initStep2(cmdLine)
  File "/nix/store/0qh2p7y4331h1y9jl5gd6fsxqbpwjlnh-wikidpad-master-2019-07-31/WikidPad/lib/pwiki/MainApp.py", line 419, in initStep2
    self.startPersonalWikiFrame(cmdLine)
  File "/nix/store/0qh2p7y4331h1y9jl5gd6fsxqbpwjlnh-wikidpad-master-2019-07-31/WikidPad/lib/pwiki/MainApp.py", line 724, in startPersonalWikiFrame
    wikiFrame = PersonalWikiFrame(None, -1, "WikidPad", self.wikiAppDir,
  File "/nix/store/0qh2p7y4331h1y9jl5gd6fsxqbpwjlnh-wikidpad-master-2019-07-31/WikidPad/lib/pwiki/PersonalWikiFrame.py", line 356, in __init__
    self.initializeGui()
  File "/nix/store/0qh2p7y4331h1y9jl5gd6fsxqbpwjlnh-wikidpad-master-2019-07-31/WikidPad/lib/pwiki/PersonalWikiFrame.py", line 2355, in initializeGui
    self.windowLayouter.realize()
  File "/nix/store/0qh2p7y4331h1y9jl5gd6fsxqbpwjlnh-wikidpad-master-2019-07-31/WikidPad/lib/pwiki/WindowLayout.py", line 459, in realize
    objWin = self.createWindowFunc(pr, proxyWin)
  File "/nix/store/0qh2p7y4331h1y9jl5gd6fsxqbpwjlnh-wikidpad-master-2019-07-31/WikidPad/lib/pwiki/PersonalWikiFrame.py", line 2618, in createWindow
    tree = WikiTreeCtrl(self, parent, -1, winName[:-4])
  File "/nix/store/0qh2p7y4331h1y9jl5gd6fsxqbpwjlnh-wikidpad-master-2019-07-31/WikidPad/lib/pwiki/WikiTreeCtrl.py", line 1320, in __init__
    self.refreshGeneratorLastCallTime = time.clock()  # Initial value
AttributeError: module 'time' has no attribute 'clock'
```

**Comment by MingStar** [comment]
At the beginning of the file `WikidPad.py`, I've added the following lines:

```
import time
time.clock = time.perf_counter
```

This makes it work for Python 3.8+

**Comment by OpenSourceEverything** [comment]
I would say if @MingStar 's solution is backwards compatible with versions before python 3.8 in addition to python 3.8 and above this is a valid solution and there should be a PR, otherwise I would assume a more robust solution that conditionally checks everyone for the time.clock feature's availability and executes differently.

I wouldnt mind working on and testing a PR for this  but would like some input from other developers.

**Comment by benkinooby** [comment]
Hi, this issue is only one of many deprecation issues as python and modules move on.
I started to implement branches targeting specific version-combinations of python, wxpython and wxwidgets/wxGTK that I happen to have on my system:

- https://github.com/WikidPad/WikidPad/tree/python3.11_wxpython4.2.0_wxwidgets3.2
- https://github.com/WikidPad/WikidPad/tree/python3.12.3_wxpython4.2.1_wxwidgets3.2.2.1
- https://github.com/WikidPad/WikidPad/tree/python3.14.4_wxpython4.2.5_wxwidgets3.2.8.1

@OpenSourceEverything I see that you forked WikidPad and implemented your own fixes. If you're up for some collaboration I'd be happy to discuss ambitions and figure out how to join forces.

I will keep this issue open on purpose, as a reminder that WikidPad main branch is slowly but certainly drifting into obsolescence.

**Comment by OpenSourceEverything** [comment]
Hi @benkinooby, yes, I’d be interested in helping.

After looking again at my fork, I think the most useful path is probably not to make my fork the base. I made some pragmatic Linux-first choices to get WikidPad running and tested again, but I also removed/de-emphasized Windows/mac release support more aggressively than is probably appropriate for upstream. however, if the windows hostile aggressive approach is acceptable, we can look into that.

Your compatibility branches look closer to the core maintenance problem: getting WikidPad through modern Python/wxPython/wxWidgets changes while keeping the upstream project intact. I’d like to help finish that work and contribute the useful parts of my fork back in smaller pieces, especially CI, Linux setup/testing, and release automation.


Let me know what you think....

Would you prefer help on the Python 3.11 branch first, or should we target the Python 3.14/wxPython 4.2.5 branch as the forward branch?

My suggested approach would be:


I’m happy to start by testing one of your branches and opening PRs for the CI pieces that do not force a Linux-only direction.

**Comment by benkinooby** [comment]
Hi @OpenSourceEverything your response is the best response I could hope for! Great!

I welcome your thoughts and considerations: I'm torn between
* maintaining Win/Mac support (can't really test it myself though)
* keeping maintenance burden low by focusing on Linux only (thus breaking Mac/Win - i.e. following your approach)

Ignore the python 3.11 branch. Python 3.11 will be EOL Oct 31, 2026 
The python 3.14 is the branch of relevance (next to master ofc).

Please allow me some time to figure out:
* priority of win/mac support vs. linux-only support
* do this all on master or an extra branch
* bring all this up in an appropriate issue/discussion (instead of hijacking this one)

Looking forward to collaboration!
