### ISSUE TITLE
TypeError: EvtHandler.Connect(): argument 1 has unexpected type 'wxSourceId'

### ISSUE THREAD

**Issue by benkinooby** [WikidPad/WikidPad#82]
Hi,

I am on branch **python3.8plus** which seems to have the latest commits.

Starting WikidPad will fail with the following error
```
user@linux ~/WikidPad $ python WikidPad.py
08:36:49: Debug: Adding duplicate image handler for 'Windows bitmap file'
Traceback (most recent call last):
  File "/home/user/WikidPadGit/WikidPad/WikidPad/lib/pwiki/MainApp.py", line 227, in OnInit
    return self.initStep2(cmdLine)
  File "/home/user/WikidPadGit/WikidPad/WikidPad/lib/pwiki/MainApp.py", line 419, in initStep2
    self.startPersonalWikiFrame(cmdLine)
  File "/home/user/WikidPadGit/WikidPad/WikidPad/lib/pwiki/MainApp.py", line 724, in startPersonalWikiFrame
    wikiFrame = PersonalWikiFrame(None, -1, "WikidPad", self.wikiAppDir,
  File "/home/user/WikidPadGit/WikidPad/WikidPad/lib/pwiki/PersonalWikiFrame.py", line 356, in __init__
    self.initializeGui()
  File "/home/user/WikidPadGit/WikidPad/WikidPad/lib/pwiki/PersonalWikiFrame.py", line 2290, in initializeGui
    self.mainAreaPanel = MainAreaPanel(self, self, -1)
  File "/home/user/WikidPadGit/WikidPad/WikidPad/lib/pwiki/MainAreaPanel.py", line 100, in __init__
    self.Bind(wx.EVT_MENU, self.OnCloseThisTab,
  File "/usr/lib/python3.10/site-packages/wx/core.py", line 1406, in _EvtHandler_Bind
    event.Bind(self, id, id2, handler)
  File "/usr/lib/python3.10/site-packages/wx/core.py", line 1477, in Bind
    target.Connect(id1, id2, et, function)
TypeError: EvtHandler.Connect(): argument 1 has unexpected type 'wxSourceId'
OnInit returned false, exiting...
```
I am using

Python 3.10.6
[wxpython 4.0.7-r2](https://wxpython.org/news/2019-11-12-wxpython-407post1-release/index.html)
[wxGTK 3.0.5.1](https://wxwidgets.org/news/2020/04/wxwidgets-3.0.5-released/)
Configuring wxwidgets (wxGTK) from default gtk3 to gtk2 will result in the same behaviour as shown above.

The way I see it, there is something wrong/incompatible with the way WikidPad uses wx, specifically `event.Bind()` and consequently `event.Connect()`

https://docs.wxpython.org/4.0.7/wx.EvtHandler.html#wx.EvtHandler.Bind
https://docs.wxpython.org/4.0.7/wx.EvtHandler.html#wx.EvtHandler.Connect

Anyone has already dealt with that issue or has helpful input / guidance how to solve it?

**Comment by benkinooby** [comment]
This issue (that I opened) is no longer relevant and was fixed by #83
