### ISSUE TITLE
Files disappearing entirely

### ISSUE THREAD

**Issue by Diplotomodon** [WikidPad/WikidPad#87]
Opened the program today and every single project apart from the default WikidPad help pages had disappeared. 

These are the only lines that appear in the error log since July (when I started using the program with no issues):

```
Version: 'wikidPad 2.2' Session start: 2022-10-29 16:25:58
Traceback (most recent call last):
  File "pwiki\wikidata\original_gadfly\WikiData.pyo", line 2017, in storeDataBlock
  File "pwiki\wikidata\original_gadfly\DbStructure.pyo", line 105, in execSql
  File "lib/gadfly\database.py", line 380, in execute
  File "lib/gadfly\store.py", line 1159, in flush
  File "lib/gadfly\store.py", line 1256, in log
  File "lib/gadfly\store.py", line 1237, in restart
IOError: [Errno 13] Permission denied: u'C:\\Program Files (x86)\\WikidPad\\WikidPadHelp\\data\\wikidb.gfl'
```

Using the latest version obviously. Should be able to recover most of my work from an external backup, but this seems like an important issue to fix regardless.

**Comment by benkinooby** [comment]
Hi @Diplotomodon  - I am aware this response is _very_ late. This looks like a permission issue when accessing the DB.
Note, that the gadfly database is just the index of your actual wiki data, to speed up search and other operations.
Your data is stored as wiki text files and is still around (you might have permission issues there too though).

Read more about the use of databases in wikidpad here:

https://wikidpad.sourceforge.net/help/WikiDatabase.html
